# Generated by Django 5.2.8 on 2026-01-04 00:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property",
                        to="auth.group",
                        verbose_name="Associated Group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
            },
        ),
        migrations.CreateModel(
            name="GuestsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="bookings.property",
                        verbose_name="Property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guest",
                "verbose_name_plural": "Guests",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DocsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_name",
                    models.CharField(
                        help_text="Descriptive name for the document", max_length=200
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("aadhaar", "Aadhaar Card"),
                            ("passport", "Passport"),
                            ("driving_license", "Driving License"),
                            ("voter_id", "Voter ID"),
                            ("other", "Other ID"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="guest_docs/%Y/%m/%d/", verbose_name="Document file"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="bookings.property",
                        verbose_name="Property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="StayData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest_count",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                            (11, "11"),
                            (12, "12"),
                            (13, "13"),
                            (14, "14"),
                            (15, "15"),
                            (16, "16"),
                            (17, "17"),
                            (18, "18"),
                            (19, "19"),
                            (20, "20"),
                        ],
                        default=1,
                        help_text="Number of guests",
                    ),
                ),
                ("check_in_date", models.DateField(default=datetime.date.today)),
                ("check_out_date", models.DateField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "coming_from",
                    models.CharField(
                        blank=True,
                        help_text="Where are the guests coming from?",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "terms_agreed",
                    models.BooleanField(
                        default=False, verbose_name="Terms read and agreed"
                    ),
                ),
                (
                    "terms_agreed_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Terms agreed at"
                    ),
                ),
                (
                    "form_filled",
                    models.BooleanField(default=False, verbose_name="Form filled"),
                ),
                (
                    "form_filled_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Form filled at"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_stays",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "documents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="stays",
                        to="bookings.docsdata",
                        verbose_name="Documents",
                    ),
                ),
                (
                    "guests",
                    models.ManyToManyField(
                        related_name="stays",
                        to="bookings.guestsdata",
                        verbose_name="Guests",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stays",
                        to="bookings.property",
                        verbose_name="Property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stay",
                "verbose_name_plural": "Stays",
                "ordering": ["-check_in_date"],
            },
        ),
    ]
