# Generated by Django 5.2.8 on 2026-01-04 00:35

import bookings.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=bookings.models.generate_booking_code,
                        max_length=7,
                        unique=True,
                        verbose_name="Booking Code",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional: When should this link expire?",
                        null=True,
                        verbose_name="Expiration Date",
                    ),
                ),
                (
                    "accessed_count",
                    models.IntegerField(default=0, verbose_name="Times Accessed"),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Accessed"
                    ),
                ),
                (
                    "stay",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_code",
                        to="bookings.staydata",
                        verbose_name="Associated Stay",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Code",
                "verbose_name_plural": "Booking Codes",
                "ordering": ["-created_at"],
            },
        ),
    ]
