# Generated by Django 5.2.8 on 2026-01-04 00:45

import django.db.models.deletion
import django_summernote.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_bookingcode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseRules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Terms and Conditions",
                        max_length=200,
                        verbose_name="Title displayed to guests",
                    ),
                ),
                (
                    "content",
                    django_summernote.fields.SummernoteTextField(
                        help_text="House rules content with rich text editing support.",
                        verbose_name="Rules Content",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="Increment when making major updates"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="house_rules",
                        to="bookings.property",
                        verbose_name="Property",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "House Rules",
                "verbose_name_plural": "House Rules",
            },
        ),
    ]
