# Generated by Django 5.2.8 on 2026-01-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_houserules"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="location_url",
            field=models.URLField(
                blank=True,
                help_text="Google Maps location URL for the property",
                null=True,
                verbose_name="Google Maps URL",
            ),
        ),
    ]
